name: 'AutoRealeseDraft'
description: 'My Desc'
author: 'Your name or organization here'
outputs:
  release-url:              # change this
    description: 'The URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
